### ISSUE TITLE
Game crashes with certain custom songs

### ISSUE THREAD

**Issue by Moonep** [The-New-Platinum-Team/PlatinumQuest-Dev#111]
I wanted to add custom music from fallout 1. For whatever reason one song works but the others crash the game when I try to play them.

I've made sure that all of them fit the ogg format.

**Comment by TheGreatAutismo** [comment]
The bitrate also matters. If the bitrate is incorrect, that's likely the cause of the issue. I'm not sure what the correct bitrate is myself, but try looking at the songs already in PQ

**Comment by Moonep** [comment]
thanks

**Comment by Moonep** [comment]
Solution: go into audacity and re-export it as .ogg

alternative if ffmpeg is your cup of tea,
ffmpeg -i file.ogg file.ogg
