### ISSUE TITLE
Part of DA HOUSE has no collision

### ISSUE THREAD

**Issue by TheGreatAutismo** [The-New-Platinum-Team/PlatinumQuest-Dev#113]
Will update the issue name if the cause is found
https://discord.com/channels/346034549962047488/820530618987315220/1100545444620279840

**Comment by RandomityGuy** [comment]
Lol its the interior collision detection update again, the same kind that broke Nukesweeper

**Comment by thearst3rd** [comment]
Lmao, the scaling for that interior is so small that it's smaller than RandomityGuy's threshold for colliding with very small objects:
https://github.com/The-New-Platinum-Team/MBExtender-Dev/commit/a6532a5554f588a6b0a23c0695222ed6d8135ba8
![image](https://user-images.githubusercontent.com/7307599/235369519-dd642340-c2ab-43be-9ba7-80390f3d1740.png)

2x10^-11 < 1x10^-8

We just need to make that threshold even smaller

**Comment by thearst3rd** [comment]
Fixed in https://github.com/The-New-Platinum-Team/MBExtender-Dev/commit/3a9dd3b20fee35636a499d918ac6598e260bac74
