### ISSUE TITLE
Many Marble Blast Platinum Levels are Missing Easter Eggs They Had in Older Versions

### ISSUE THREAD

**Issue by TheGreatAutismo** [The-New-Platinum-Team/PlatinumQuest-Dev#128]
Supposedly they were removed for feeling samey, but not a lot of them were even removed in the first place, and it didn't change anything. Plus, you're bound to have some hiding spots be similar if you hide an egg in over 100 levels

https://discord.com/channels/346034549962047488/1156468065760985088

**Comment by RandomityGuy** [comment]
Added in https://github.com/The-New-Platinum-Team/PlatinumQuest-Dev/pull/138
