### ISSUE TITLE
Load custom levels only when needed, due to time spent loading

### ISSUE THREAD

**Issue by main-gi** [The-New-Platinum-Team/PlatinumQuest-Dev#27]
people are reporting that starting the game takes longer w/ custom levels, especially with CLA installed

**Comment by RandomityGuy** [comment]
Forgot to close.
Fixed in https://github.com/The-New-Platinum-Team/PlatinumQuest-Dev/commit/9e312b173b4ce925fba576114802ade7a8203d12
One time overhead when loading the thing for the first time, subsequent loads should be much faster.
