### ISSUE TITLE
"White boxes" crash

### ISSUE THREAD

**Issue by main-gi** [The-New-Platinum-Team/PlatinumQuest-Dev#36]
People experience crashes that often are foreshadowed by some of the UI elements turning into 'white boxes'.

I have not personally had the 'white boxes' happen except at the very last frame of a crash. When that happens, some HUD elements, like the hundredths digit on the timer, turn into an orange box instead of the intended bitmap, on the frame of the crash

**Comment by RandomityGuy** [comment]
Fixed with engine upgrade
