### ISSUE TITLE
Hunt Hard Mode option doesn't deselect when you join a server

### ISSUE THREAD

**Issue by HiGuyMB** [The-New-Platinum-Team/PlatinumQuest-Dev#38]
Help my blast doesn't work because i turned the option on, on my server, but i joined someone else who has it off

**Comment by RandomityGuy** [comment]
Fixed in https://github.com/The-New-Platinum-Team/PlatinumQuest-Dev/commit/e4219c52bb9f1a78a4ee36670e9400fd38935dd6 probably
