### ISSUE TITLE
Invalid Packet on Mac

### ISSUE THREAD

**Issue by RandomityGuy** [The-New-Platinum-Team/PlatinumQuest-Dev#47]
Terrible bug, gotta fix when motivation happens.

**Comment by RandomityGuy** [comment]
No more!

**Comment by dylanskripnik-crypto** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/8f9dede7-a00a-4c25-835f-0b6db87015e7" />
