### ISSUE TITLE
Scores Still Save to Main Leaderboard with Certain Modes Enabled

### ISSUE THREAD

**Issue by TheGreatAutismo** [The-New-Platinum-Team/PlatinumQuest-Dev#89]
Competitive Mode, Party Mode, and Double Spawns, among others, should disallow scores from being saved to the main leaderboard. (A) separate leaderboard(s) could maybe be made for them

**Comment by RandomityGuy** [comment]
Competitive mode, party spawns and double spawns modes have been removed making it invalid. Issue may be reopened if these modes get added back in the future at some point

**Comment by TheGreatAutismo** [comment]
Competitive Mode and Double Spawns have since been added back, but the latter does not save scores to the level's leaderboard as suggested.
