### ISSUE TITLE
Update MBG level previews

### ISSUE THREAD

**Issue by RandomityGuy** [The-New-Platinum-Team/PlatinumQuest-Dev#96]
Chore

**Comment by thearst3rd** [comment]
I started doing this and realized that it's creating .png files instead of .dds files. Is there a way to get the game to generate them in the same format as the originals or do I convert them after the fact?

CC @Connierollstheball

**Comment by RandomityGuy** [comment]
https://vvvv.org/contribution/dds-converter

**Comment by thearst3rd** [comment]
Done in a8975416cfcb0f081e67ca8db681e61c66cac1e9
